# Generated by Django 2.2.3 on 2019-07-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='stock_buy_in_price',
            field=models.FloatField(default=0.0),
        ),
    ]
