# Generated by Django 2.2.3 on 2019-07-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=100)),
                ('topic_text', models.CharField(max_length=500)),
                ('topic_date', models.DateTimeField(verbose_name='create_date')),
            ],
        ),
    ]
