# Generated by Django 2.2.3 on 2019-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190710_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_date',
            field=models.DateField(verbose_name='create_date'),
        ),
    ]
